name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_ghPages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy GH-Pages
        run: |
          git config --global user.email ${{secrets.MY_EMAIL}}
          git config --global user.name ${{secrets.MY_USERNAME}}
          git remote set-url origin https://${{secrets.MY_PERSONAL_TOKEN_PUBLIC}}@github.com/${{github.repository}}
          yarn deploy